name: dicee_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^0.18.0
  path_provider: ^2.0.9
  google_fonts: ^2.3.2
  animated_text_kit: ^4.2.1
  url_launcher: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  color_dark: "000000"


flutter:
  uses-material-design: true
  assets:
      - images/
      - assets/


  fonts:
    - family: Bangers
      fonts:
        - asset: fonts/Bangers-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf